# LambdaTest AI Cloud Configuration
project_id: "01KA1JA719VE8CAHS435KG8J96"
folder_id: "01KA1JBE1FAQJ0FW0MCR85ZGJK"
assignee: 1094938
environment_id: 1
test_url: "https://ecommerce-playground.lambdatest.io/"